/* system.h 
 * 
 * Machine generated header file for SOPC system as defined in 
 * C:\Users\ben\Documents\My Dropbox\School\ECE 4740\ComputerOrganization1\nios_system.ptf
 */ 

#ifndef __SYSTEM_H__
#define __SYSTEM_H__

/* 
DO NOT MODIFY THIS FILE 

 This file is automatically generated by the Altera Debug Client according to the 
 ptf file generated by the SOPC Builder. If you are not sure of what you are doing, 
 do not change this file. If you do change this file, please note that your changes 
 will be overwritten and lost when this file is generated again. 

DO NOT MODIFY THIS FILE
*/ 


/******************************************************************************
*                                                                             *
* License Agreement                                                           *
*                                                                             *
* Copyright (c) 2003 Altera Corporation, San Jose, California, USA.           *
* All rights reserved.                                                        *
*                                                                             *
* Permission is hereby granted, free of charge, to any person obtaining a     *
* copy of this software and associated documentation files (the "Software"),  *
* to deal in the Software without restriction, including without limitation   *
* the rights to use, copy, modify, merge, publish, distribute, sublicense,    *
* and/or sell copies of the Software, and to permit persons to whom the       *
* Software is furnished to do so, subject to the following conditions:        *
*                                                                             *
* The above copyright notice and this permission notice shall be included in  *
* all copies or substantial portions of the Software.                         *
*                                                                             *
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  *
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    *
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE *
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      *
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     *
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         *
* DEALINGS IN THE SOFTWARE.                                                   *
*                                                                             *
* This agreement shall be governed in all respects by the laws of the State   *
* of California and by the laws of the United States of America.              *
*                                                                             *
******************************************************************************/
/*
 * onchip_memory2_0/s1 configuration
 */
#define ONCHIP_MEMORY2_0_S1_NAME "/dev/onchip_memory2_0"
#define ONCHIP_MEMORY2_0_S1_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_0_S1_BASE 0x00008000
#define ONCHIP_MEMORY2_0_S1_SPAN 32768
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_IGNORE_AUTO_BLOCK_TYPE_ASSIGNMENT 1
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE "onchip_memory2_0"
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_SIZE_VALUE 32768
#define ONCHIP_MEMORY2_0_WRITEABLE 1
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_CONTENTS_INFO "QUARTUS_PROJECT_DIR/onchip_memory2_0.hex 1290119239 "
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE "M4K"
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE "Automatic"
#define ONCHIP_MEMORY2_0_USE_SHALLOW_MEM_BLOCKS 0
#define ONCHIP_MEMORY2_0_INSTANCE_ID "NONE"

#endif /* __SYSTEM_H__ */
